# Generated by Django 3.1.4 on 2021-01-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_dj', '0002_auto_20210110_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='signed_id',
            new_name='signed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='subscriber_id',
            new_name='subscriber',
        ),
    ]
